### ISSUE TITLE
Add `Server::poll_accept`

### ISSUE THREAD

**Issue by carllerche** [hyperium/h2#184]
It is not clear when `poll` will return `Ready(None)`. Specifically, will it do so when there are no more streams to accept or when the connection is closed?

It is possible for the remote to send a GOAWAY which prevents any *new* streams but allows in-flight streams to continue. If `poll` returns `Ok(None)` on `GOAWAY`, when using the combinator API, the `Server` value will be dropped without being able to call `Server::poll_close` to advance the state of the in-flight streams.

I believe the following should happen:

* `poll` will not return `Ready(None)` until the connection is fully finalized (`poll_close` returns `Ready`).
* An additional fn, `poll_accept` is added that will return `Ready(None)` once a GOAWAY frame is received, the max stream ID is received, or any other state is reached that prevents further streams from being received. This allows the caller to be notified that no further streams will be sent.

**Comment by seanmonstar** [comment]
From what I can tell, `poll` and `poll_close` both work as described in the issue description, and all that is needed is for the addition of `poll_accept` to return `Ready(None)` even if the connection isn't completely closed, but GOAWAY has started.

**Comment by seanmonstar** [comment]
If that's the case, then adding this isn't a breaking change, and probably doesn't need to hold up 0.1 release.

**Comment by carllerche** [comment]
@seanmonstar I have not personally verified this, so if `poll` behaves as described, we can punt post 0.1.

**Comment by nox** [comment]
I assume that's `Connection::poll_accept`, that already exists but is `doc(hidden)`. Feel free to reopen if I'm wrong.
