### ISSUE TITLE
Support CONNECT requests

### ISSUE THREAD

**Issue by carllerche** [hyperium/h2#234]
`CONNECT` requests have a number of special requirements. Currently, no focus has been put on making this work.

This is a continuation of #228.

**Comment by nox** [comment]
@kornelski did a PR to support some details at the end of January, does anyone know what's missing still?

**Comment by nox** [comment]
AFAIK, this can be closed thanks to #534, I don't think any other requirement is related to this crate itself, just proxies using it.
