### ISSUE TITLE
State of HTTP/2 push

### ISSUE THREAD

**Issue by vbrandl** [hyperium/h2#291]
What is the state of HTTP/2 server push in h2? I couldn't find anything about it in the documentation. Are there any plans to implement it in the future?

**Comment by carllerche** [comment]
Push isn’t a priority for me personally. I don’t have any plans to work on it. I would be happy to help guide anyone who wants to try to do the work. 

Push is mostly wired through internally. It would mostly be a question of finishing the work, adding the public api, and write docs.

**Comment by vbrandl** [comment]
How big of an issue do you think this will be? I've written some Rust already, but I've never actively worked on a bigger codebase. Also I'm not familiar with the h2 push spec, but I might be interested in implementing it.

**Comment by carllerche** [comment]
I am not sure tbh. I think some of the inner work is done, but I don't recall how much off the top of my head.

It would probably be more than a trivial change.

**Comment by carllerche** [comment]
I can try to write up what is left next time I dive into the code base.

**Comment by Karrq** [comment]
Why is this issue closed? Support for PUSH seems very experimental so far...
See #412

**Comment by Karrq** [comment]
What's the status on this? It can't be done? I'd like to know if there's a plan for this to be implemented properly, @seanmonstar

**Comment by seanmonstar** [comment]
@Karrq the status is the same. The features worked on in this library depend on the priorities of the contributors offering their work. Would you be able to dedicate time to improving the situation here? From reading the linked issues, there doesn't seem like *too* much more is needed.

**Comment by Karrq** [comment]
Unfortunately I need the functionality but I don't know how to implement it, otherwise I would have already.
I was wondering for the status because the issue is closed, maybe it can be reopened and tagged with help wanted or something...
Thank you anyways
