### ISSUE TITLE
Handling server authority

### ISSUE THREAD

**Issue by carllerche** [hyperium/h2#317]
https://httpwg.org/specs/rfc7540.html#authority

> HTTP/2 relies on the HTTP/1.1 definition of authority for determining whether a server is authoritative in providing a given response (see [RFC7230], Section 9.1). This relies on local name resolution for the "http" URI scheme and the authenticated server identity for the "https" scheme (see [RFC2818], Section 3).

I don't think we do anything to handle this. Given that the `h2` crate is not provided a host name to resolve, it is unclear if we should do something or punt to hyper.

**Comment by nox** [comment]
This can live outside h2 indeed, so let's close this issue. Feel free to reopen if you think I closed this too eagerly.
