### ISSUE TITLE
Validate server authority

### ISSUE THREAD

**Issue by carllerche** [hyperium/h2#323]
From the spec:

> The server MUST include a value in the :authority pseudo-header field for which the server is authoritative (see Section 10.1). A client MUST treat a PUSH_PROMISE for which the server is not authoritative as a stream error (Section 5.4.2) of type PROTOCOL_ERROR.

Something similar probably applies to requests / responses.

The h2 crate is decoupled from the transport and, as such, doesn't have a notion of what authority the server has.

Ref: https://github.com/carllerche/h2/pull/314#discussion_r225670609

**Comment by eggyal** [comment]
How about adding to `client::ResponseFuture` a `fn push_promises_validated(&mut self, authority: &uri::Authority) -> PushPromises` and deprecating `push_promises`, thus requiring the user to provide the expected authority for this library to validate?

**Comment by eggyal** [comment]
I've sketched out an idea below.

Admittedly this proposes additions to a number of libraries (including std, although perhaps something suitable already exists?) but I think it's broadly a sensible approach, that keeps everything nicely encapsulated?  What do you think @carllerche @seanmonstar ?

```
// std?
trait AuthorizationChallenge {
    type Result = bool;
}
trait Authorizer<C: AuthorizationChallenge> {
    fn authorize(&self, challenge: C) -> C::Result;
}

// http
struct HttpAuthorizationChallenge<'a> {
    scheme: &'a uri::Scheme,
    authority: &'a uri::Authority,
}
impl AuthorizationChallenge for HttpAuthorizationChallenge {}

// hyper
impl Authorizer<HttpAuthorizationChallenge<'_>> for TcpStream {
    fn authorize(&self, challenge: HttpAuthorizationChallenge) -> bool {
        // resolve challenge.authority.host()
        // combine with challenge.authority.port() if present, else default for challenge.scheme
        // thus obtaining a SocketAddr
        // compare with self.peer_addr()?
        todo!()
    }
}

// hyper-tls
impl Authorizer<HttpAuthorizationChallenge> for TlsStream {
    fn authorize(&self, challenge: HttpAuthorizationChallenge) -> bool {
        // test challenge.authority.host() against self.0.peer_certificate()
        // (ideally using native libraries, but this isn't currently exposed by native_tls nor ought it to be...)
        todo!()
    }
}

// h2
// require provided io stream to implement Authorize<HttpAuthorizationChallenge>
// then, upon decoding a PUSH_PROMISE frame (in codec), call io.authorize(challenge) and either proceed (if passed) or reset stream with PROTOCOL_ERROR (otherwise)
```

**Comment by seanmonstar** [comment]
I personally think it's fine that `h2` doesn't do this, since it doesn't have all the information. It's possible for a user who does have all the information to check it (though I do suppose people will probably forget to do so...).

**Comment by nox** [comment]
This can live outside h2 indeed, so let's close this issue. Feel free to reopen if you think I closed this too eagerly.
