### ISSUE TITLE
Close client connection

### ISSUE THREAD

**Issue by LinkTed** [hyperium/h2#336]
Is there a way to close a client connection?

**Comment by seanmonstar** [comment]
Dropping all other handles (`SendRequest`, `ResponseFuture`, `SendStream`, `RecvStream`) for a certain connection should close it.

**Comment by panpur** [comment]
@seanmonstar 
If I drop those handles, will the connection be closed in synchronous manner?
The reason is, I'm working on app to measure performance of http2 request.
One of the KPI is disconnect time.
So I'm wondering whether this is achievable if it's asynchronous.

**Comment by nox** [comment]
It is asynchronous in the sense that the drop code of the types mentioned in the previous comment will just wake up the connection task and if the connection task sees there are no more references it will close itself.

**Comment by nox** [comment]
Closing this because it's not very actionable.
