### ISSUE TITLE
Update to std::future

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/h2#385]

**Comment by seanmonstar** [comment]
As a note, @sgrif has been working on this.

**Comment by Kobzol** [comment]
I looked at @sgrif's h2/sg-std-future branch and it seems that he also decided to switch to Rust 2018, pretty much in the same time as I pushed the 2018 PR here (https://github.com/hyperium/h2/pull/383). Just a heads-up to @sgrif that the PR was merged, so maybe it would be better to rebase first to avoid a monster merge conflict later :)
