### ISSUE TITLE
Investigate CVEs related to HTTP/2

### ISSUE THREAD

**Issue by mikedilger** [hyperium/h2#393]
It might be a good idea to check to see if h2 is vulnerable to any of these HTTP/2 issues that Netflix has drawn attention to:

https://github.com/Netflix/security-bulletins/blob/master/advisories/third-party/2019-002.md

Hacker News comment thread: https://news.ycombinator.com/item?id=20688178

**Comment by nilslice** [comment]
A recent patch to Go's implementation might be useful to look at: https://github.com/golang/go/commit/7139b45d1410ded14e1e131151fd8dfc435ede6c

**Comment by seanmonstar** [comment]
I want to take time to properly audit, but as a quick update: many of the issues don't affect this library, since we don't build unbounded buffers of frame acks, not use stream priorities.

**Comment by nox** [comment]
Is this issue actionable? Should we close it? I feel like that's the kind of issue that just stays open forever and just looks scary.

**Comment by seanmonstar** [comment]
I guess it _could_ be actionable, if someone wanted to take the full list and analyze h2 and come out the other side with pass/fail marks. As I mentioned before, I looked at most of them a couple years ago, and h2 isn't affected, but I didn't double check _all_ of them.

At this point, if no one has wanted to investigate further, it's probably just time to close and if someone _does_ investigate and finds something, it costs nothing to open a new issue.
