### ISSUE TITLE
h2::RecvStream no longer implements Stream.

### ISSUE THREAD

**Issue by bluejekyll** [hyperium/h2#426]
In a down the middle case of implementing over RecvStream, this doesn't matter much, but the issue is that this creates a difficult situation in regards to writing unit tests over functions that take a RecvStream as an argument.

In previous versions RecvStream implemented Stream making this straight forward. It's not obvious at the moment how to build a generic interface over RecvStream such that mock tests can be build to test functionality of implementations without requiring an underlying connection.

For example, this is a previous test that was somewhat simple to implement before:

https://github.com/bluejekyll/trust-dns/blob/master/crates/https/src/https_server.rs#L195

where `message_from` used to be generic over a Stream wrapped in `Request<S>`:

https://github.com/bluejekyll/trust-dns/blob/master/crates/https/src/https_server.rs#L26-L28

Any thoughts on how we could achieve a similar interface with the new `async fn` based `data()` and the non-`Stream`, `RecvStream`?

**Comment by LucioFranco** [comment]
Hey! So we've been exposing `Stream` implementations under the `unstable-stream` feature that is not enabled by default. This may just be a case of missing the feature?

https://github.com/hyperium/h2/blob/86e53054a6/src/share.rs#L452

This is also a general pattern we've been using in all the hyperium repos.

**Comment by bluejekyll** [comment]
I -just- noticed that when looking at updating the docs! Apologies for the spam.

**Comment by LucioFranco** [comment]
No worries, we 100% could document this stuff better :)

**Comment by bluejekyll** [comment]
async/await has a lot of stuff in transition.
