### ISSUE TITLE
Replace/reduce usage of unsafe code for BytesStr

### ISSUE THREAD

**Issue by jhinch** [hyperium/h2#440]
Most of the `unsafe` code used when interacting with `BytesStr` is during construction to ensure that the bytes supplied are in valid utf8 but without performing validation on the input. It turns out that all usages of `BytesStr::from_utf8_unchecked` can be replaced with two functions, `fn from(str: &str) -> BytesStr` and `const fn from_static(str: &'static str) -> BytesStr` and I can't see any reason for there to be a difference in performance.

I have already coded up the changes before I realised that the contribution guide suggested that a ticket should be raised before creating a PR. You can find my changes here: https://github.com/jhinch/h2/commit/5229090af42f53dbac8973760327705d668f142f. If you are happy for me to go ahead, I'll make it a PR.

**Comment by nox** [comment]
Please make a PR :)

**Comment by nox** [comment]
I filed #540.

**Comment by jhinch** [comment]
Glad to hear this is being considered.
