### ISSUE TITLE
Support for h2 over UDS

### ISSUE THREAD

**Issue by gila** [hyperium/h2#442]
When using tonic/h2 over UDS, I think it should be possible to allow the '/' in the authority header. This looks related to #345 where Jan is also mentioning potential issues might arise once h2 would be used over UDS.  

From RFC-3986:

```
For example, the "file" URI  scheme is defined so that no authority, 
an empty host, and "localhost"  all mean the end-user's machine, 
whereas the "http"  scheme considers a missing authority or
empty host invalid.
```

A longer description of the issue can be found at https://github.com/hyperium/tonic/issues/243

Perhaps it would be possible to support file:// (and then also perhaps the unix:// scheme) and depending on that, determine if the authority header is valid for the current scheme?

**Comment by saschagrunert** [comment]
Hey, any update on this one? I think the addition would make sense, wouldn't it?

**Comment by nox** [comment]
AFAICT grpc-go stopped sending a malformed authority so I'm closing this.

**Comment by teozkr** [comment]
For what it's worth, I'm still getting this with grpc-go v1.38.0, which was released on 2021-05-19 (a few weeks after your comment):

> 2021-11-23T22:02:25.675177Z DEBUG Connection{peer=Server}: h2::server: malformed headers: malformed authority (b"/foo/bar.sock"): invalid uri character

I'll try to reproduce with grpc-go v1.42.0 (the current latest release).

**Comment by teozkr** [comment]
Same issue with grpc-go v1.42.0.
