### ISSUE TITLE
Connection::poll()

### ISSUE THREAD

**Issue by keepsimple1** [hyperium/h2#466]
In docs generated , it describes the method `Connection::poll()` at [here](https://docs.rs/h2/0.2.5/h2/server/index.html#inbound-streams) but I cannot find the doc or implementation of this method (not on this [page](https://docs.rs/h2/0.2.5/h2/server/struct.Connection.html#method.poll)). Is the doc accurate about this method, or maybe I missed something?

**Comment by sfackler** [comment]
That looks like a typo - the method is actually named `accept`.
