### ISSUE TITLE
Calculating pseudo header name length is incorrect

### ISSUE THREAD

**Issue by kadfak** [hyperium/h2#472]
When calculating pseudo header name length, [`stringify`](https://doc.rust-lang.org/std/macro.stringify.html) macro is used in helper macros like this: `stringify!($ident)`. While the expected results are `method`, `status`, `path`, etc., the current implementation incorrectly produces <code>$&nbsp;ident</code> and uses its length for all calculations.

Relevant lines: [[0]](https://github.com/hyperium/h2/blob/ceae69b4687b446666b4491771fe94a08a90cc82/src/frame/headers.rs#L828), [[1]](https://github.com/hyperium/h2/blob/ceae69b4687b446666b4491771fe94a08a90cc82/src/frame/headers.rs#L920), [[2]](https://github.com/hyperium/h2/blob/ceae69b4687b446666b4491771fe94a08a90cc82/src/frame/headers.rs#L945)

**Comment by seanmonstar** [comment]
Well, that's a woops. Also, it's surprising that is even allowed (what's the point of `stringify!($nonexistant)` over `"$nonexistant"`).
