### ISSUE TITLE
Could the server.rs example integrate with rustls?

### ISSUE THREAD

**Issue by heibor** [hyperium/h2#480]
As a beginner, I think if the [server.rs](https://github.com/hyperium/h2/blob/master/examples/server.rs) could provide the TLS it would be better. I'm trying to integrate with rustls, but it's a little hard to me. Who can provide a server sample integrated with rustls?
Thanks.

**Comment by seanmonstar** [comment]
Hyper doesn't pick any TLS implementation as the preferred one. So we don't include an example for the various libraries.

**Comment by algesten** [comment]
@heibor for context, h2 might be lower level than you want. 

You're probably encountering that rustls doesn't implement `AsyncWrite` and `AsyncRead`. Rustls is not async out of the box, and to make it async you need to do some trickery with wrapping it. I've got such wrapper here: https://github.com/algesten/hreq/blob/master/src/tls.rs but I think there are some crates doing it too.

**Comment by heibor** [comment]
I found warp's [tls.rs](https://github.com/seanmonstar/warp/blob/master/examples/tls.rs) is a good place to start. And the correct way to generate my own self-signed certificate is:
```
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout server.key -out server.crt
```
Is it right?
Thanks for your advice. @algesten
