### ISSUE TITLE
h2 turns on the log feature of tracing, 

### ISSUE THREAD

**Issue by msvbg** [hyperium/h2#481]
This issue is the analog of https://github.com/hyperium/hyper/issues/2273 for h2.

h2 turns on the log feature of tracing, which can be a little bit annoying if you are using another library which records a lot of tracing spans. By using h2 in my project, my logs get filled with traces from a different library. It would be nice if it were possible to turn this off.

**Comment by max-heller** [comment]
Addressed by #501, I believe
