### ISSUE TITLE
tokio = "0.3.0"

### ISSUE THREAD

**Issue by incker** [hyperium/h2#492]
New version of tokio is released
current version of tokio is 0.2 in Cargo.toml

Better upgrade, to avoid downloading two versions of tokio in projects

**Comment by taiki-e** [comment]
See #491

**Comment by Urhengulas** [comment]
Fixed by #491 

@seanmonstar Can this please be part of a new release soon?

**Comment by seanmonstar** [comment]
Yes, this was merged. There's a few other things left to do, and it is being prepared together with hyper. The releases will likely happen at the same time.
