### ISSUE TITLE
Simple HTTP GET request

### ISSUE THREAD

**Issue by nu8** [hyperium/h2#496]
I am looking to make a simple HTTP GET request. I dont need HTTPS, I dont need
Async. I might need those later on, but to start I would just like to keep it
simple. I looked here:

https://docs.rs/h2/0.2.7/h2/client/index.html

but the example has HTTPS and Async, which I dont need either. Also it is
confusing because it lists two addresses:

~~~
127.0.0.1:5928
https://www.example.com/
~~~

why are two addresses listed? If you want to cURL something, you just do
`curl https://www.example.com/`, you dont need a second address. Also I notice
the example even streams the response. As with the HTTPS and Async, thats a nice
feature, but I would prefer a simple example that just returns the entire body
as a byte array. I also checked here:

https://github.com/hyperium/h2/blob/master/examples/client.rs

but the example seems pretty much same as other example. To give an idea of what
I am looking for, here is an example from the `minreq` crate:

~~~rust
use minreq;

fn main() -> Result<(), minreq::Error> {
   let s_in = "http://speedtest.lax.hivelocity.net";
   let o = minreq::get(s_in).send()?;
   let s_out = o.as_str()?;
   print!("{}", s_out);
   Ok(())
}
~~~

This example works with HTTPS too, just change the URL. Is H2 able to make a
simple request like this?

**Comment by seanmonstar** [comment]
This library is lower level, implementing the HTTP/2 protocol and exposing all its events. It sounds like you just want easy-as-possible HTTP requests, in which case I'd recommend using [reqwest](https://crates.io/crates/reqwest), and enabling the `blocking` feature, and then you can make simple blocking requests and not worry about most of the details.

**Comment by nu8** [comment]
request has 108 dependencies, according to [my script](//github.com/nu8/cove/tree/master/rust-deps). I am interested in H2 because my script reporting only 29 dependencies. So if its possible to make a simple request with H2 then I would like to explore that. It seems that is the case, I guess I will try to figure it out myself.

**Comment by nu8** [comment]
Actually, I just noticed that H2 doesnt utilize `native-tls`:

https://crates.io/crates/native-tls

I have found that crate to be very useful with Windows. So H2 is probably not a
good fit for me anyway. Thanks

**Comment by seanmonstar** [comment]
h2 doesn't use any specific TLS transport. It works with rustls, openssl, native-tls, or any other transport that implements the required traits.

**Comment by nu8** [comment]
Fair enough, but none of those are included:

https://github.com/hyperium/h2/blob/cbbdd305b1afc1eaf19f2e3b26f9419048041e7d/Cargo.toml#L44-L56

so anyone who chooses this crate, will also have to choose a TLS crate. I didnt
want to have to choose an HTTP crate in the first place, I think Rust should
have one built in like Go or others.

So you can understand that I certainly dont want to also have to choose a TLS
crate.

**Comment by seanmonstar** [comment]
That's why I suggested you use `reqwest`. It's put all the pieces together for you. Rust is different than Go, it's best to try to learn why and why it's decided things.
