### ISSUE TITLE
[HELP] 65536 byte limit 

### ISSUE THREAD

**Issue by Tonyce** [hyperium/h2#523]
<img width="661" alt="截屏2021-03-12 下午8 20 10" src="https://user-images.githubusercontent.com/7351139/110962880-69e1d500-838c-11eb-870a-6469557a09df.png">

How can i solve it

**Comment by seanmonstar** [comment]
h2 doesn't manage flow control automatically, [you need to say when you're ready for more data](https://docs.rs/h2/0.3.1/h2/struct.FlowControl.html).

Possibly something as simple as `body.flow_control().release_capacity(buf.len())`, but the option is there to *not* release capacity if you want to force the remote to pause or slow down.

**Comment by Tonyce** [comment]
@seanmonstar Thanks for your help, as you said, I did the same thing in the code, but it did not meet my expectations

my code here:

https://github.com/Tonyce/tokio-h2-grpc/blob/main/src/main.rs#L75-L86

this confuses me.
