### ISSUE TITLE
malformed authority error with HTTP2 and gRPC

### ISSUE THREAD

**Issue by arthurlm** [hyperium/h2#525]
I am running h2 as a service in k8s to process gRPC requests.

Some clients of my service (envoy HTTP proxy) got error responses du to invalid authority field:
```
[2021-03-18T10:54:07Z DEBUG h2::server] malformed headers: malformed authority (b"extension/k8s-namespace-arthurlm-test/auth-server"): invalid uri character 
```

I do not have any ability to change envoy behavior: it need to use HTTP2 + TLS + cannot change request headers and payload.
I agree this authority is a little bit unexpected...

Should we make this kind of Authority allowed ?
Is there any way to allow h2 processing the request even if `Authority::parse` failed ?

**Comment by nox** [comment]
Did you file an issue against the envoy HTTP proxy so they don't emit malformed authorities

**Comment by nox** [comment]
#442

**Comment by arthurlm** [comment]
Unfortunately no 😞.

I have fork h2 and just  show a log warn if authority field parsing fail.
See diff: https://github.com/hyperium/h2/compare/master...arthurlm:master

I would be happy to merge this change in h2 but I do not know if this policy is the expected one by h2.

**Comment by nox** [comment]
I am not sure what you mean by "unfortunately no". Isn't Envoy [a FOSS project](https://github.com/envoyproxy/envoy)? Personally I don't think a patch to allow completely malformed authorities should be accepted.

**Comment by nox** [comment]
Let's move this discussion to #442 please, as it is the same issue.
