### ISSUE TITLE
Suspicious documentation clause about enable_push - missing negation?

### ISSUE THREAD

**Issue by vi** [hyperium/h2#645]
In [`client::Builder::enable_push`](https://docs.rs/h2/latest/h2/client/struct.Builder.html#method.enable_push) documentation:

> `pub fn enable_push(&mut self, enabled: bool) -> &mut Self;`

> This value is included in the initial SETTINGS handshake. When set [?!], the server MUST NOT send a push promise. Setting this value to value to false in the initial SETTINGS handshake guarantees that the remote server will never send a push promise.

Is it meant to be "when set **to `false`**"?

**Comment by seanmonstar** [comment]
I believe you are correct, thanks for catching this. Want to send a PR?
