### ISSUE TITLE
`max_send_buffer_size` documentation states default is 400 MB. It is 400 KB.

### ISSUE THREAD

**Issue by Protryon** [hyperium/h2#718]
The documentation for `max_send_buffer_size` state the default is 400 MB. It appears to be 400 KB from looking at the code. We we're pretty alarmed by this at first.

**Comment by seanmonstar** [comment]
Oh, good catch! Where was the mistake, in hyper or in h2? Want to submit a PR?

**Comment by Protryon** [comment]
It was in `h2` documentation. Yeah I'll submit one later today I suppose.
