### ISSUE TITLE
assertion failed: DEFAULT_MAX_FRAME_SIZE

### ISSUE THREAD

**Issue by makorne** [hyperium/h2#804]
Hi! Tank you for your great crates!

I tried to set the max message size 50mb.

[Allow setting a message max size](https://github.com/hyperium/tonic/issues/264)
```
Server::builder()
        .max_frame_size(50 * 1024 * 1024) //50Mb
```
But got the error: 
```
thread 'tokio-runtime-worker' panicked at  .cargo/registry/src/index.crates.io-6f17d22bba15001f/h2-0.4.5/src/frame/settings.rs:91:13:
assertion failed: DEFAULT_MAX_FRAME_SIZE <= val && val <= MAX_MAX_FRAME_SIZE
```
How to set the max message size 50mb?

**Comment by seanmonstar** [comment]
You cannot set it that high. The HTTP/2 spec defines the valid range between 16kb and 16mb: https://httpwg.org/specs/rfc9113.html#rfc.section.4.2

**Comment by makorne** [comment]
But when I set ` .max_frame_size(16 * 1024 * 1024 -  1)`
The error anyway:
`code: OutOfRange, message: "Error, decoded message length too large: found 6242911 bytes, the limit is: 4194304 bytes",`

**Comment by seanmonstar** [comment]
That error is not coming from h2, and likely not coming from tonic either. Tonic knows how to decode a message split over multiple DATA frames, and can also send over split DATA frames. The error message sounds like it is coming from the other side (your client?).
