### ISSUE TITLE
Improve noise of logs

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/h2#81]
There is a lot logged, and while it's useful, it can make it hard to see slightly more important information in the logs. Perhaps we can promote many of the logs to debug level, especially those with useful arguments included. Some of the less important logs could stay at trace (things like `poll`), or possibly be removed entirely.

I suspect @olix0r has noticed the noise :)

**Comment by nox** [comment]
Has anyone thought about this those last 4 years? If not, we should probs close this issue.
