### ISSUE TITLE
Question about flow control

### ISSUE THREAD

**Issue by DjordjeNikolasevic** [hyperium/h2#821]
I am writing a custom protocol relying on HTTP/2. The protocol relies on maintaing integrity of data frames between sender and receiver, meaning that I need to avoid a situation where a data frame gets involuntarily split by the application layer (h2 library). I noticed that the implementation in hyper is not satisfactory, as it relies on h2 internal flow control buffering which will send a chunk of a submitted frame as soon as there is some increment in capacity:
https://github.com/hyperium/hyper/blob/eaf2267cdc148604469fb09da22646f31710107a/src/proto/h2/mod.rs#L121-L124

I was thinking of using `poll_capacity` in h2 to specificially wait until there is capacity for the entire data frame to fit, prior to calling `send_data`. I am aware that `poll_capacity` may need to be called multiple times, until the full amount of capacity is assigned. In my prototyping, this works very well:

```
/// Should only be called after a non-0 capacity was requested for the stream.
pub fn wait_for_capacity(stream: h2::SendStream<Bytes>, target: usize) -> WaitForCapacity {
    WaitForCapacity {
        stream: Some(stream),
        requested_capacity: target,
    }
}

pub struct WaitForCapacity {
    stream: Option<h2::SendStream<Bytes>>,
    requested_capacity: usize,
}

impl WaitForCapacity {
    fn stream(&mut self) -> &mut h2::SendStream<Bytes> {
        self.stream.as_mut().unwrap()
    }
}

impl Future for WaitForCapacity {
    type Output = h2::SendStream<Bytes>;

    fn poll(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        loop {
            let increment = ready!(self.stream().poll_capacity(cx)).unwrap();

            let act = self.stream().capacity();
            println!("Available capacity: {:?}. Requested capacity: {:?}. Increment: {:?}", act, self.requested_capacity, increment);

            assert_ne!(act, 0);

            if act >= self.requested_capacity {
                return Poll::Ready(self.stream.take().unwrap());
            }

            println!("Still waiting...");
        }
    }
}

async fn handle(socket: TcpStream) -> Result<(), Box<dyn Error>> {
            ...

            let size = 1024;
            let bytes: Vec<u8> = vec![0; size];
            send.reserve_capacity(size);
            send = wait_for_capacity(send, size).await;
            send.send_data(bytes.into(), false).unwrap();
}
```

However, I am worried about this snippet from official docuemtnation:
[https://docs.rs/h2/latest/h2/struct.SendStream.html#flow-control](https://docs.rs/h2/latest/h2/struct.SendStream.html#flow-control)
"To avoid throttling data on a connection, the caller should not reserve capacity until ready to send data and once any capacity is assigned to the stream, the caller should immediately send data consuming this capacity. There is no guarantee as to when the full capacity requested will become available. For example, if the caller requests 64 KB of data and 512 bytes become available, **the caller should immediately send 512 bytes of data**."

What are the consequences of not sending a chunk of data as soon as some capacity becomes available? I am aware of potential deadlocks due to buffering of WINDOW_UPDATE frames which are not guaranteed to be sent on every `release_capacity `call. However, based on code inspection, it seems that the threshold can be at most the half of initial window_size:
https://github.com/hyperium/h2/blob/cffea952853c98df0a0c96d51b128cb3a5fbd8b2/src/proto/streams/flow_control.rs#L101

So,  I should be fine if I use the following configuration `INITIAL_WINDOW_SIZE > 2 * MAX_FRAME_SIZE`. I also plan to rule out connection level flow control and rely on stream level flow control only, by setting `INITIAL_CONNECTION_WINDOW_SIZE` to max value.

Are there any other potentially dangerous things that I should be mindful of and take into consideration? Is the flow control API supposed to be used this way?

**Comment by seanmonstar** [comment]
That recommendation from the docs is based on how `h2` exposes "reserving" capacity. Since there is capacity both for the connection and the stream, it notifies you when there is N capacity on both. Since we consider that capacity reserved on the connection, we won't give it to another stream.

If you only got half of what you want, and keep waiting, and there was another stream that _could_ have sent, it will just wait.

Thinking this through even farther, I suppose it's possible the remote peer could have specifically tried to slow a specific stream, _want_ you to send on multple, by giving 20 bytes to the connection, but only 10 to that stream. There's no guarantee that the remote will ever give you more capacity while you wait, that's entirely "allowed" by the specification.

---

If you control both sides, then perhaps you can depend on that never happening. :shrug:
