### ISSUE TITLE
Dropping a `Body` implicitly release remaining capacity?

### ISSUE THREAD

**Issue by carllerche** [hyperium/h2#90]
`Body` is used to release capacity on a stream. If the body is dropped and the remaining capacity is not released, then that connection level capacity is lost.

**Comment by seanmonstar** [comment]
*Probably*. Once the `Body` is dropped, there is no more API surface to release the capacity. Technically, it's possible that the user has taken the chunks, and dropped the body, but not dropped the chunks, and so the resource capacity is still in use... But, there's a lot of things a user could do that that would by-pass any smart thing we might do.

Like just copying the chunks into a `Vec<u8>`...

**Comment by seanmonstar** [comment]
When all user references to a stream are dropped (`SendStream`, `RecvStream`, `ReserveCapacity`), the unreleased stream capacity will now be given back to the connection automatically.
